version: "3.7"     # version 정보를 작성합니다.

services:           # service 목록을 정의합니다.
  node:             # service의 이름입니다.
    image: discordgamblebot  # 해당 service에서 사용할 image입니다.
    restart: always         # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행합니다.
    container_name: "node"  # container의 name을 정의합니다.
    ports:                  # service port를 정의합니다.
      - "3000:3000"         # local:container
    depends_on:             # 실행순서를 설정한다. (mongodb시작 후 실행)
      - mongodb
  mongodb:          # service의 이름입니다.
    image: mongo    # 해당 service에서 사용할 image입니다.
    restart: always # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행합니다.
    volumes:        # container -> local로 mount할 수 있습니다.
      - type: bind 
        source: /home/geonyeong/localdb # local 경로
        target: /data/db  # container 내부에서의 경로
    container_name: "mongo" # container의 name을 정의합니다.
    ports:                # service port를 정의합니다.
      - "27017:27017"     # local:container